version: "3"

services:  
  keycloak_main:    
    image: quay.io/keycloak/keycloak:20.0.0        
    command: start-dev
    environment:      
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_postgres
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB_NAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}      
    ports:      
      - "8580:8080"      
    depends_on:      
      postgres_svr:
        condition: service_healthy
    networks:
      network_sso:
        ipv4_address: "10.0.0.2"    

  keycloak_postgres: 
    image: postgres:10
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'    
    environment:
      # Environment Variables expecially for Postgres
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    healthcheck:
      test: "exit 0"
    ports:
      - "5432:5432"
    networks:
      network_sso:
        ipv4_address: "10.0.0.3"
networks:  
  network_sso:
    ipam:
    # IP Address management
      driver: default
      # default = bridge
      config:
        - subnet: "10.0.0.0/24"