version: "3"

services:  
  keycloak_main:    
    image: quay.io/keycloak/keycloak:20.0.0        
    environment:    
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME:  sso.xneek.ru
      # KC_DB: postgres
      # KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      # KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      # KC_DB_URL: "jdbc:postgresql://postgres/${KEYCLOAK_DB_NAME}"
    ports:
      - "${KEYCLOAK_PORT}:8080"
    command:
        - start-dev 

#   keycloak_postgres: 
#     image: postgres:15  
#     environment:
#       POSTGRES_DB: ${KEYCLOAK_DB_NAME}
#       POSTGRES_USER: ${KEYCLOAK_DB_USER}
#       POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
#     volumes:
#       - ~/keycloak_sso_vol:/var/lib/postgresql/data
# volumes: 
#   keycloak_sso_vol: