version: "3.9"
services:
  postgres:
    container_name: postgres_keycloack
    image: "postgres:13.2"
    volumes:
      - ./db-data:/var/lib/postgresql/data/
    env_file:
      - ./database.dev.env
    ports:
      - "5432:5432"
    networks:
      - backend
  keycloak:
    container_name: keycloak_blog
    image: "jboss/keycloak:15.0.2"
    env_file:
      - ./keycloak.dev.env
    depends_on:
      - "postgres"
    ports:
      - "8180:8080"
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge