version: "3"

services:  
  keycloak_main:    
    image: quay.io/keycloak/keycloak:20.0.0        
    command: start-dev
    environment:      
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_postgres
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB_NAME}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}      
    ports:
      - "${KEYCLOAK_PORT}:8080"
    
    depends_on:      
      - keycloak_postgres
    networks:
      - network_sso  

  keycloak_postgres: 
    image: postgres:10
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB'    
    environment:
      # Environment Variables expecially for Postgres
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    healthcheck:
      test: "exit 0"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - network_sso
    volumes:
      - keycloak_sso_vol:/var/lib/postgresql/data 
networks:
  network_sso:

volumes: 
  keycloak_sso_vol: