name: Deploy pohodnik-sso
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: Deploy pohodnik sso
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.ETERNAL_SSH_HOST }}
          username: ${{ secrets.ETERNAL_SSH_USER }}
          key: ${{ secrets.ETERNAL_KEY }}
          script: |
            cd ~/
            rm -rf pohodnik-sso
            git clone git@github.com:pohodnik/pohodnik-sso.git
            sudo chmod -R 755 pohodnik-sso
            cd pohodnik-sso
            docker-compose down --rmi all --remove-orphans
            echo KEYCLOAK_DB_PASSWORD="${{ secrets.KEYCLOAK_SECRET }}" >> .env
            echo KEYCLOAK_ADMIN_USERNAME="${{ secrets.KEYCLOAK_USER }}" >> .env
            echo KEYCLOAK_ADMIN_PASSWORD="${{ secrets.KEYCLOAK_PASSWORD }}" >> .env
            docker-compose up -d
      - name: Send telegramm notofication
        run: curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_TO }} -d parse_mode=html -d text="$MESSAGE" >> /dev/null
        env:
          MESSAGE: |
            ✔ pohodnik-sso succesfully deployed.
            https://pohodnik.tk
            <i>${{ github.event.head_commit.message }}</i>
            ${{ github.actor }}
